name: TimeConvertor
description: Converts time between timezones
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^5.0.0
  flutter_spinkit: ^5.1.0
  dots_indicator: ^2.1.0
  flutter_native_timezone: ^2.0.0
  shared_preferences: ^2.0.17
  json_annotation: ^4.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  # only re-enable when wanted
  # flutter_launcher_icons: ^0.7.4
  flutter_native_splash: ^2.2.17
  build_runner: ^2.3.3
  json_serializable: ^6.6.1

flutter_native_splash:
  color: "#2196f3"
  android: true
  ios: true
  color_android: "#2196f3"
  color_ios: "#2196f3"
  android_12:
    color: "#2196f3"
    image: assets/icon.png

flutter_icons:
  android: true
  ios: true
  image_path: assets/icon.png
  adaptive_icon_background: "#2196f3"
  adaptive_icon_foreground: "assets/icon.png"

flutter:
  uses-material-design: true

  assets:
   - assets/
